### PR TITLE
Use contracts instead of concrete implementation (managers) that can't be resolved via IoC.

### LINKED ISSUE #179: CacheManager dependency resolving error
On the dev branch I am getting the following error:
`Unresolvable dependency resolving [Parameter #0 [ <required> $app ]] in class Illuminate\Cache\CacheManager`

```
in Container.php line 823
at Container->resolveNonClass(object(ReflectionParameter)) in Container.php line 798
at Container->getDependencies(array(object(ReflectionParameter)), array()) in Container.php line 771
at Container->build('Illuminate\Cache\CacheManager', array()) in Container.php line 626
at Container->make('Illuminate\Cache\CacheManager', array()) in Application.php line 393
at Application->make('Illuminate\Cache\CacheManager') in Container.php line 837
at Container->resolveClass(object(ReflectionParameter)) in Container.php line 800
at Container->getDependencies(array(object(ReflectionParameter)), array()) in Container.php line 771
at Container->build('Tymon\JWTAuth\Providers\Storage\Illuminate', array()) in Container.php line 626
at Container->make('Tymon\JWTAuth\Providers\Storage\Illuminate', array()) in Application.php line 393
at Application->make('Tymon\JWTAuth\Providers\Storage\Illuminate') in LumenServiceProvider.php line 207
at LumenServiceProvider->getConfigInstance('providers.storage') in LumenServiceProvider.php line 88
at LumenServiceProvider->Tymon\JWTAuth\Providers\{closure}(object(Application), array()) in Container.php line 733
at Container->build(object(Closure), array()) in Container.php line 626
at Container->make('tymon.jwt.provider.storage', array()) in Application.php line 393
at Application->make('tymon.jwt.provider.storage') in Container.php line 1157
at Container->offsetGet('tymon.jwt.provider.storage') in LumenServiceProvider.php line 139
at LumenServiceProvider->Tymon\JWTAuth\Providers\{closure}(object(Application), array()) in Container.php line 733
at Container->build(object(Closure), array()) in Container.php line 626
at Container->make('tymon.jwt.blacklist', array()) in Application.php line 393
at Application->make('tymon.jwt.blacklist') in Container.php line 1157
at Container->offsetGet('tymon.jwt.blacklist') in LumenServiceProvider.php line 101
at LumenServiceProvider->Tymon\JWTAuth\Providers\{closure}(object(Application), array()) in Container.php line 733
at Container->build(object(Closure), array()) in Container.php line 626
at Container->make('tymon.jwt.manager', array()) in Application.php line 393
at Application->make('tymon.jwt.manager') in Container.php line 1157
at Container->offsetGet('tymon.jwt.manager') in LumenServiceProvider.php line 126
at LumenServiceProvider->Tymon\JWTAuth\Providers\{closure}(object(Application), array()) in Container.php line 733
at Container->build(object(Closure), array()) in Container.php line 626
at Container->make('tymon.jwt.auth', array()) in Application.php line 393
at Application->make('tymon.jwt.auth', array()) in helpers.php line 38
at app('tymon.jwt.auth') in AuthController.php line 49
at AuthController->postLogin(object(Request))
at call_user_func_array(array(object(AuthController), 'postLogin'), array(object(Request))) in Container.php line 502
at Container->call(array(object(AuthController), 'postLogin'), array()) in Application.php line 1328
at Application->callControllerCallable(array(object(AuthController), 'postLogin'), array()) in Application.php line 1293
at Application->callLumenController(object(AuthController), 'postLogin', array(true, array('uses' => 'App\Http\Controllers\Auth\AuthController@postLogin'), array())) in Application.php line 1264
at Application->callControllerAction(array(true, array('uses' => 'App\Http\Controllers\Auth\AuthController@postLogin'), array())) in Application.php line 1232
at Application->callActionOnArrayBasedRoute(array(true, array('uses' => 'App\Http\Controllers\Auth\AuthController@postLogin'), array())) in Application.php line 1217
at Application->handleFoundRoute(array(true, array('uses' => 'App\Http\Controllers\Auth\AuthController@postLogin'), array())) in Application.php line 1138
at Application->Laravel\Lumen\{closure}() in Application.php line 1370
at Application->sendThroughPipeline(array(), object(Closure)) in Application.php line 1144
at Application->dispatch(null) in Application.php line 1084
at Application->run() in index.php line 28
```

### PR DESCRIPTION
**Pull request by crynobone**
Alternative to #219 and fixes #179 

Signed-off-by: crynobone <crynobone@gmail.com>

### CODE REVIEW

**Comment by crynobone** [comment]
The only issue with this changes is that `Guard` doesn't have `onceById` contract. Only the implementing class has it.

**Comment by tymondesigns** [comment]
Thanks!

File: src/Providers/Storage/Illuminate.php [hunk 1]
```diff
@@ -11,13 +11,13 @@
 
 namespace Tymon\JWTAuth\Providers\Storage;
 
-use Illuminate\Cache\CacheManager;
 use Tymon\JWTAuth\Contracts\Providers\Storage;
+use Illuminate\Contracts\Cache\Store as StoreContract;
```
Comment (mod3st) [inline src/Providers/Storage/Illuminate.php]: Did you tested it? Laravel cannot instatiate Cache\Store contract.
CacheManager is an implementation of Cache\Factory contract, so it class should be use instead of Cache\Store.

In my opinion laravel Managers are so flexible, so there's no need to use contracts in this case (jwt packages allows custom cache/auth provider classes).

Comment (crynobone) [inline src/Providers/Storage/Illuminate.php]: Sorry about that, send a fix to #271

> In my opinion laravel Managers are so flexible, so there's no need to use contracts in this case

It either go with a contract that can be resolved with IoC (AuthManager and CacheManager is not aliased in Lumen Framework, unlike Laravel https://github.com/laravel/lumen-framework/blob/5.1/src/Application.php#L1656-L1659), or swap the way jwt packages resolve the providers class.
